// File generated by FlutterFire CLI.
// This file should be in: lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx0L8uZIHDOMaEXeAhrHUmgzETj1SijEQ',
    appId: '1:164217598709:web:a47b880a1ca5a322fb0bbc',
    messagingSenderId: '164217598709',
    projectId: 'stock-manager-510eb',
    authDomain: 'stock-manager-510eb.firebaseapp.com',
    storageBucket: 'stock-manager-510eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDferFOFRHzTcoPluQiKWwcVZh7GH4Y1Pc',  // Replace with your Android API key
    appId: '1:164217598709:android:9089704fc44e1a79fb0bbc',    // Replace with your Android App ID
    messagingSenderId: '164217598709',
    projectId: 'stock-manager-510eb',
    storageBucket: 'stock-manager-510eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',      // Replace with your iOS API key
    appId: 'YOUR_IOS_APP_ID',        // Replace with your iOS App ID
    messagingSenderId: '164217598709',
    projectId: 'stock-manager-510eb',
    storageBucket: 'stock-manager-510eb.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManager',  // Replace with your iOS bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',      // Replace with your iOS API key (same as iOS)
    appId: 'YOUR_IOS_APP_ID',        // Replace with your iOS App ID
    messagingSenderId: '164217598709',
    projectId: 'stock-manager-510eb',
    storageBucket: 'stock-manager-510eb.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManager',  // Replace with your macOS bundle ID
  );
}